### ISSUE TITLE
Problem saving players

### ISSUE THREAD

**Issue by BloodDragon2580** [c0nnex/7dtdmanager#3]
Stats works now very nice. thx for the Quick Update.
So i have a other Error for you.

http://pastebin.com/WHeLrg3P

See the end of the file it gives problems with save the player.xml

I hope its ok with the Log^^ And i hope its ok for the error reporting.

**Comment by c0nnex** [comment]
Kein Problem .. Sich mit fremden Federn schmücken schon ....

**Comment by DarkBrain2580** [comment]
Ja sry fals es darum gehen sollte: Copyright (c) 2015 DarkBrain info@universal-fighters.de

Habe die Sachen per suchen und ersetzen ersetzt dadurch kamm das zu stande habe ich selber heute erst gesehen.

Das wird nachher noch geändert das ist so nicht gewollt versprochen.
